-- BEGIN;
DROP TABLE IF EXISTS answer_likes;
DROP TABLE IF EXISTS answers;
DROP TABLE IF EXISTS question_likes;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;
-- COMMIT;
